services:
  webpage:
    container_name: webpage
    image: php:apache
    environment:
      - USERNAME=toto
      - PASSWORD=python
    ports:
      - "80:80"
    networks:
      - stuent-list-networks
    depends_on:
      - api
    volumes:
      - ./website:/var/www/html
  api:
    container_name: api
    image: api:v1.0
    ports:
      - "5000"
    volumes:
      - ./student_api/student_age.json:/data/student_age.json
    networks:
      - stuent-list-networks
networks:
  stuent-list-networks:
    driver: bridge
    name: stuent-list-networks